### ISSUE TITLE
Remove node14 only features

### ISSUE THREAD

**Issue by msfeldstein** [holtwick/create-estrella#1]
When i use `npm init estrella <project-name>` It creates a build.config.js that [uses the nullish coalescing operator](https://github.com/holtwick/create-estrella/blob/master/template/build.config.js#L14-L16).  This means i need to update node to v14+, but estrella itself [targets node v12+](https://github.com/rsms/estrella/blob/master/package.json#L39).  Can we remove this feature which doesn't exist in node12?

**Comment by holtwick** [comment]
Thanks! I fixed it and now use a very basic setup https://github.com/rsms/estrella/issues/9#issuecomment-701124622
